# Generated by Django 6.1 on 2026-08-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
