# Generated by Django 3.2.11 on 2026-06-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
