# Generated by Django 4.2.30 on 2026-07-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodiespot', '0002_auto_20260706_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='foods/')),
                ('description', models.TextField()),
            ],
        ),
    ]
