# Generated by Django 4.2.30 on 2026-08-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_cashfree_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cashfree_order_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
