# Generated by Django 4.2.30 on 2026-08-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_cashfree_order_id_alter_booking_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online Payment')], default='Online', max_length=20),
        ),
    ]
