# Generated by Django 4.2.30 on 2026-08-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
    ]
