# Generated by Django 4.2.30 on 2026-09-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Online Payment Successful'), ('Cash', 'Cash'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
